# fly.toml app configuration file generated for restapi-bloodline-dna on 2024-12-19T10:00:00.000Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'restapi-bloodline-dna'
primary_region = 'sin'  # Singapore region for better performance in Asia

[build]

[deploy]
  release_command = 'echo "Deployment starting..."'

[env]
  NODE_ENV = 'production'
  WEBSITES_PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    timeout = '5s'
    path = '/api'

[vm]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[vm.http_service.concurrency]]
  hard_limit = 25
  soft_limit = 20
  type = 'connections'

[metrics]
  port = 9091
  path = '/metrics'

# Enable process restart on failure
[processes]
  app = 'pnpm start'

# Machine restart policy
[restart]
  policy = 'on-failure'