[build]
# Railway will automatically detect and use the Dockerfile

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig."asia-southeast1-eqsg3a"]
numReplicas = 1