export const COLLECTION_NAME = {
    SETTING: 'Setting',
    ADMINISTRATIVE_CASE: 'Administrative_Case',
    USER: 'User',
    BLOG: 'Blog',
    BLOG_LOG: 'Blog_Log',
    BLOG_CATEGORY: 'Blog_Category',
    SERVICE: 'Service',
    APPOINTMENT: 'Appointment',
    REVIEW: 'Review',
    KIT: 'Kit',
    SAMPLE: 'Sample',
    REGISTRATION_FORM: 'RegistrationForm',
    RESULT: 'Result',
    PAYMENT: 'Payment',
    TRANSACTION: 'Transaction',
    APPOINTMENT_LOG: 'AppointmentLog',
    DEPARTMENT: 'Department',
    STAFF_PROFILE: 'StaffProfile',
    SLOT: 'Slot',
    ATTENDANCE: 'Attendance',
    REFUND: 'Refund',
    RESERVATION: 'Reservation',
};
